# Generated by Django 5.2.4 on 2025-11-11 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadeEscolar',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('vinculo', models.CharField(max_length=50, verbose_name='Vínculo')),
                ('turmaouDisciplina', models.CharField(max_length=50, verbose_name='Turma ou Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do Tipo do Produto')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('credencial', models.IntegerField(primary_key=True, serialize=False, verbose_name='Credencial')),
                ('nome', models.CharField(max_length=100, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=8, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Produto')),
                ('marca', models.CharField(max_length=50, null=True, verbose_name='Marca')),
                ('devo_ou_nao', models.BooleanField(default=False, verbose_name='Devolutivo ou não')),
                ('tipoProduto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('idEmprestimo', models.AutoField(primary_key=True, serialize=False, verbose_name='Empréstimo')),
                ('dataSaida', models.DateField(null=True, verbose_name='Data de Saída')),
                ('dataDevolucao', models.DateField(null=True, verbose_name='Data de Devolução')),
                ('comunidadeEscolar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comunidadeescolar')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.usuarios')),
            ],
        ),
    ]
