# Generated by Django 5.2.6 on 2025-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('credencial', models.TextField(max_length=100)),
                ('senha', models.TextField(max_length=100)),
            ],
        ),
    ]
