# Generated by Django 5.2.7 on 2025-11-27 11:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadeEscolar',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('vinculo', models.CharField(max_length=50, verbose_name='Vínculo')),
                ('turmaouDisciplina', models.CharField(max_length=50, verbose_name='Turma ou Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Produto')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('devo_ou_nao', models.BooleanField(default=False, verbose_name='Devolutivo ou não')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do Tipo do Produto')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('credencial', models.CharField(primary_key=True, serialize=False, verbose_name='Credencial')),
                ('nome', models.CharField(max_length=100, verbose_name='Usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('idEmprestimo', models.AutoField(primary_key=True, serialize=False, verbose_name='Empréstimo')),
                ('dataSaida', models.DateField(null=True, verbose_name='Data de Saída')),
                ('dataDevolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('comunidadeEscolar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comunidadeescolar')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produtos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='tipoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoproduto'),
        ),
    ]
