# Generated by Django 5.2.7 on 2025-11-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='Master'),
        ),
    ]
