# Generated by Django 5.2.7 on 2025-11-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Produto')),
                ('marca', models.CharField(max_length=50, null=True, verbose_name='Marca')),
                ('tipoProduto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoproduto')),
            ],
        ),
    ]
