# Generated by Django 5.2.7 on 2025-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarios_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
