# Generated by Django 5.2.7 on 2025-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='devo_ou_nao',
            field=models.BooleanField(default=False, verbose_name='Devolutivo ou não'),
        ),
    ]
