# Generated by Django 5.2.7 on 2025-11-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emprestimo_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
    ]
