# Generated by Django 5.2.7 on 2025-10-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_credencial_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadeEscolar',
            fields=[
                ('matricula', models.IntegerField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('vinculo', models.CharField(max_length=50)),
                ('turmaouDisciplina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('idEmprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('dataSaida', models.DateField()),
                ('dataDevolucao', models.DateField()),
                ('comunidadeEscolar', models.ManyToManyField(to='core.comunidadeescolar')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('idEntrega', models.AutoField(primary_key=True, serialize=False)),
                ('dataSaida', models.DateField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idEmprestimo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('idTipoProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('credencial', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='entrega',
            name='produto',
            field=models.ManyToManyField(to='core.produtos'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='idTipoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoproduto'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='usuario',
            field=models.ManyToManyField(to='core.usuarios'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuarios',
            field=models.ManyToManyField(to='core.usuarios'),
        ),
    ]
