# Generated by Django 5.2.7 on 2025-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produtos_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
    ]
