# Generated by Django 5.2.6 on 2025-10-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comunidadeescolar_emprestimo_entrega_produtos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='idTipoProduto',
            new_name='tipoProduto',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='idEmprestimo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='idProduto',
        ),
        migrations.RemoveField(
            model_name='tipoproduto',
            name='idTipoProduto',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='produtos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.produtos'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='marca',
            field=models.CharField(max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comunidadeescolar',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='comunidadeescolar',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='comunidadeescolar',
            name='turmaouDisciplina',
            field=models.CharField(max_length=50, verbose_name='Turma ou Disciplina'),
        ),
        migrations.AlterField(
            model_name='comunidadeescolar',
            name='vinculo',
            field=models.CharField(max_length=50, verbose_name='Vínculo'),
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='comunidadeEscolar',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateField(null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataSaida',
            field=models.DateField(null=True, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='idEmprestimo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Empréstimo'),
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='tipoproduto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Tipo do Produto'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='credencial',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Credencial'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='comunidadeEscolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comunidadeescolar'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.usuarios'),
        ),
    ]
