# Generated by Django 5.2.7 on 2025-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emprestimo_datadevolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Entregue'),
        ),
        migrations.AlterField(
            model_name='comunidadeescolar',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Matrícula'),
        ),
    ]
