# Generated by Django 5.2.4 on 2025-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emprestimo_entregue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
    ]
